# -*- mode: shell-script -*-
source $HOME/.config/bash/functions.sh

alias icat="kitty +kitten icat"
alias s="kitty +kitten ssh"

alias em='emacsclient -n '
alias er='em --eval'
alias e='em -r'

# Add local directory to path"
prepend_to_path "$HOME/.local/bin"
# Add Rust to path
prepend_to_path "$HOME/.cargo/bin"

# Add Haskell to Path by executing its env file
if [[ -f "$HOME/.ghcup/env" ]]; then
    source "$HOME/.ghcup/env"
fi
